name = "Binning2D"
uuid = "d8743f86-864c-46cb-86aa-0ffcaf6e9ed2"
authors = ["Tamás K. Papp <tkpapp@gmail.com>"]
version = "0.1.0"

[deps]
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
ArgCheck = "2"
DocStringExtensions = "0.9"
StaticArrays = "1"
Statistics = "1"
julia = "1.8"
